### ISSUE TITLE
No support for nested arrays

### ISSUE THREAD

**Issue by niekvanderkooy** [lordoffox/aredis#4]
Especially within transactions, nested arrays are something which occurs quite frequently
For example,
```
MULTI
LPUSH foo bar
LPUSH foo bar
LRANGE foo 0 -1
EXEC
```
returns
```
1) (integer) 2
2) 1) "bar"
   2) "bar"
```
However, this is currently not supported by aredis. Although the `rrt_array_value` exists, the above 
`EXEC` command will return two `rrt_integer_value` types for the `LRANGE` commands, and a single `rrt_string_value` for the second command (which _does_ contain both the `bar` values, but is not formatted correctly since the string contains `bar\r\n$3\r\nbar\r\n" with a length of 3.

**Comment by lordoffox** [comment]
Hmm, I make a big mistake (lol).
To fix it, I need a big change.
Let me try to fix it.

**Comment by lordoffox** [comment]
Support nested arrays now.
